// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaiQULazU1rMa0ZW4Tt7pbIcJpIESGJLc',
    appId: '1:736540860500:web:b7613ba1e0f917e1560dc1',
    messagingSenderId: '736540860500',
    projectId: 'vibequest-da42d',
    authDomain: 'vibequest-da42d.firebaseapp.com',
    storageBucket: 'vibequest-da42d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9qbh3R834BNrJ5IJsmim1whytaLyrA0Q',
    appId: '1:736540860500:android:e8a2a2ad1ae1e94b560dc1',
    messagingSenderId: '736540860500',
    projectId: 'vibequest-da42d',
    storageBucket: 'vibequest-da42d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBReAs1OU4QU1F2ND0pxtjfZ6lZehPq_P0',
    appId: '1:736540860500:ios:622662c124566df5560dc1',
    messagingSenderId: '736540860500',
    projectId: 'vibequest-da42d',
    storageBucket: 'vibequest-da42d.firebasestorage.app',
    iosBundleId: 'com.example.vibequest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBReAs1OU4QU1F2ND0pxtjfZ6lZehPq_P0',
    appId: '1:736540860500:ios:622662c124566df5560dc1',
    messagingSenderId: '736540860500',
    projectId: 'vibequest-da42d',
    storageBucket: 'vibequest-da42d.firebasestorage.app',
    iosBundleId: 'com.example.vibequest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaiQULazU1rMa0ZW4Tt7pbIcJpIESGJLc',
    appId: '1:736540860500:web:01468a6f2ef34d30560dc1',
    messagingSenderId: '736540860500',
    projectId: 'vibequest-da42d',
    authDomain: 'vibequest-da42d.firebaseapp.com',
    storageBucket: 'vibequest-da42d.firebasestorage.app',
  );
}
